name: Code Cleanliness Check 👮🏽
on: [push]
jobs:
  check-frontend:
    name: Check Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          bun install
          bun run prepare
        working-directory: ui
        env:
          PUBLIC_API_BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}

      - name: Check Typescript and Svelte files
        run: bun check
        working-directory: ui
        env:
          PUBLIC_API_BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}

      - name: Format files
        run: bun format
        working-directory: ui
        env:
          PUBLIC_API_BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}

      - name: Ensure can build successfully
        run: bun run build
        working-directory: ui
        env:
          PUBLIC_API_BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}

      - name: Check for clean status
        run: sh scripts/ensure-git-clean.sh
        env:
          PUBLIC_API_BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}
